userwomen:
    path:     /
    defaults: { _controller: "AcmeMeetingBundle:UserWomen:index" }

userwomen_show:
    path:     /{id}/show
    defaults: { _controller: "AcmeMeetingBundle:UserWomen:show" }

userwomen_new:
    path:     /new
    defaults: { _controller: "AcmeMeetingBundle:UserWomen:new" }

userwomen_create:
    path:     /create
    defaults: { _controller: "AcmeMeetingBundle:UserWomen:create" }
    requirements: { _method: post }

userwomen_edit:
    path:     /{id}/edit
    defaults: { _controller: "AcmeMeetingBundle:UserWomen:edit" }

userwomen_update:
    path:     /{id}/update
    defaults: { _controller: "AcmeMeetingBundle:UserWomen:update" }
    requirements: { _method: post|put }

userwomen_delete:
    path:     /{id}/delete
    defaults: { _controller: "AcmeMeetingBundle:UserWomen:delete" }
    requirements: { _method: post|delete }
