acme_meeting_userwomen:
    resource: "@AcmeMeetingBundle/Resources/config/routing/userwomen.yml"
    prefix:   /userwomen

acme_meeting_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeMeetingBundle:Main:index }

main:
     path:     /
     defaults: { _controller: AcmeMeetingBundle:Main:main }

registration:
    pattern:  /registration
    defaults: { _controller: AcmeMeetingBundle:Main:registration }


login_out:
    pattern: /logout
    defaults: {_controller: AcmeMeetingBundle:Main:exitUser }


showUsers:
    pattern: /ShowOtherUsers
    defaults: {_controller: AcmeMeetingBundle:Main:showAllUsers }


showProfile:
    pattern: /profile
    defaults: {_controller: AcmeMeetingBundle:Main:showProfile }

editProfile:
    pattern: /editProfile
    defaults: {_controller: AcmeMeetingBundle:Main:editProfile }

loadImage:
    pattern: /loadImage
    defaults: {_controller: AcmeMeetingBundle:Main:loadImage }

loginAdmin:
    pattern: /loginAdmin
    defaults: {_controller: AcmeMeetingBundle:Main:loginAdmin }

adminOut:
    pattern: /adminOut
    defaults: {_controller: AcmeMeetingBundle:Main:adminOut }

ajax:
    pattern: /ajax
    defaults: {_controller: AcmeMeetingBundle:Main:ajax }